return { -- Useful plugin to show you pending keybinds.
  'folke/which-key.nvim',
  event = 'VimEnter', -- Sets the loading event to 'VimEnter'
  opts = {
    icons = {
      -- set icon mappings to true if you have a Nerd Font
      mappings = vim.g.have_nerd_font,
      -- If you are using a Nerd Font: set icons.keys to an empty table which will use the
      -- default which-key.nvim defined Nerd Font icons, otherwise define a string table
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    -- Document existing key chains
    spec = {
      { '<leader>c', group = '[C]ode', mode = { 'n', 'x' } },
      { '<leader>d', group = '[D]ocument' },
      { '<leader>r', group = '[R]ename' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>w', group = '[W]orkspace' },
      { '<leader>t', group = '[T]oggle' },
      { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      { '<leader>g', group = '[G]o/Git' },
      { '<leader>gj', desc = 'Add JSON tags' },
      { '<leader>gy', desc = 'Add YAML tags' },
      { '<leader>gi', desc = 'Implement interface' },
      { '<leader>ge', desc = 'Add if err block' },
      { '<leader>gf', desc = 'Fill struct' },
      { '<leader>gF', desc = 'Fill switch' },
      { '<leader>gc', desc = 'Show test coverage' },
      { '<leader>gC', desc = 'Clear test coverage' },
      { '<leader>o', group = '[O]pen' },
      { '<leader>z', group = 'Harpoon' },
      { '<leader>q', group = '[Q]uickfix' },
      { '<leader>x', group = 'Trouble/Diagnostics' },
      { '<leader>n', group = 'NPM/[N]ode' },
      { '<leader>a', desc = 'Swap next parameter' },
      { '<leader>A', desc = 'Swap previous parameter' },
      { '<leader>y', group = 'Clipboard', mode = { 'v' } },
      { '<leader>p', group = 'Paste', mode = { 'v' } },
      { 'gc', group = 'Comment', mode = { 'n', 'v' } },
    },
  },
}
